name: Vérification de conformité PEP8

on:
  push:
    branches:
      - main

jobs:
  pep8_check:
    name: Vérification PEP8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Installation de Python
      run: sudo apt update && sudo apt install -y python3

    - name: Vérification de conformité PEP8
      run: python3 -m pip install flake8
      run: flake8